# Generated by Django 4.1.2 on 2023-09-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Image',
        ),
    ]
